// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN6weJKkF3_2LL331Y8gQ7yHRREEeuW64',
    appId: '1:502078607982:web:8ffb3558d5cb5b898d8c7f',
    messagingSenderId: '502078607982',
    projectId: 'auth-project-kabera',
    authDomain: 'auth-project-kabera.firebaseapp.com',
    storageBucket: 'auth-project-kabera.appspot.com',
    measurementId: 'G-2LMYRLLJD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpNLf9Oy0lyxSRTrVFJ1X5ijvezKtHkqE',
    appId: '1:502078607982:android:bf6abc47296adaac8d8c7f',
    messagingSenderId: '502078607982',
    projectId: 'auth-project-kabera',
    storageBucket: 'auth-project-kabera.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOUQaVgZEWFIg2BNgElGnnpVhKDyAKcSs',
    appId: '1:502078607982:ios:2354bc2b7717e5c78d8c7f',
    messagingSenderId: '502078607982',
    projectId: 'auth-project-kabera',
    storageBucket: 'auth-project-kabera.appspot.com',
    androidClientId: '502078607982-rm46518f2ntds5n09m2jm2cs212os2tu.apps.googleusercontent.com',
    iosClientId: '502078607982-13a33vpeupqh5lpl1bspfq5npi9atq0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOUQaVgZEWFIg2BNgElGnnpVhKDyAKcSs',
    appId: '1:502078607982:ios:52893679483f83068d8c7f',
    messagingSenderId: '502078607982',
    projectId: 'auth-project-kabera',
    storageBucket: 'auth-project-kabera.appspot.com',
    androidClientId: '502078607982-rm46518f2ntds5n09m2jm2cs212os2tu.apps.googleusercontent.com',
    iosClientId: '502078607982-mo51eqdvv1p9td7gjngt6gc39233u7ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileProject.RunnerTests',
  );
}
